replicaCount: 1

image:
  repository: cbsfuturumacr.azurecr.io/pspp
  tag: 0.0.6
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: ""
  path: /

s3:
  enabled: false
  accessKeyId: ""
  endpoint: ""
  defaultRegion: ""
  secretAccessKey: ""
  sessionToken: ""
