replicaCount: 1

image:
  repository: cbsfuturumacr.azurecr.io/pspp
  tag: 0.0.6
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: ""
  path: /

s3:
  enabled: false
  accessKeyId: ""
  endpoint: ""
  defaultRegion: ""
  secretAccessKey: ""
  sessionToken: ""

init:
  personalInit: |
    #!/bin/bash
    
    # 1. Disable the XFCE Desktop 'Tip of the Day' popup
    mkdir -p ~/.config/autostart
    echo -e "[Desktop Entry]\nHidden=true" > ~/.config/autostart/xfce4-tips-autostart.desktop
    
    # 2. Disable the PSPP Application Splash/Welcome Screen
    # We copy the shortcut to the user directory to avoid root permission errors
    mkdir -p ~/.local/share/applications
    cp /usr/share/applications/org.fsf.pspp.desktop ~/.local/share/applications/ 2>/dev/null || true
    sed -i 's/Exec=psppire/Exec=psppire --no-splash/g' ~/.local/share/applications/*.desktop
