replicaCount: 1

image:
  repository: cbsfuturumacr.azurecr.io/pspp
  tag: 0.0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: ""
  path: /