apiVersion: v2
name: libreoffice
description: Test linux desktop app
type: application
version: 0.0.7

icon: https://cbs-bouwers.github.io/onyxia-repo/icons/libreoffice.png
keywords:
  - CBS
  - LibreOffice
home: https://nl.libreoffice.org/

