apiVersion: v2
name: libreoffice
description: Test linux desktop app
type: application
version: 0.0.1

icon: https://cbs-bouwers.github.io/onyxia-repo/icons/octopus.svg
keywords:
  - CBS
  - LibreOffice
home: https://nl.libreoffice.org/

