replicaCount: 1

image:
  repository: lscr.io/linuxserver/libreoffice
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3001
  targetPort: 3001

ingress:
  enabled: true
  className: nginx
  host: ""
  path: /