replicaCount: 1

image:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-i3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: ""
  path: /