apiVersion: v2
name: octopus
description: request an export audit on statistical output files.
type: application
version: 0.1.8
appVersion: "0.1.8"

icon: https://cbs-bouwers.github.io/onyxia-repo/icons/octopus.svg
keywords:
  - CBS
  - Octopus
home: https://cbs.nl/

